### ISSUE TITLE
Would u do something for the day view ?

### ISSUE THREAD

**Issue by Raklaite** [richardtallent/vue-simple-calendar-sample#1]

**Comment by richardtallent** [comment]
Hi @Raklaite,

At this time, I have no plans to add a single-day view. The existing control is heavily geared toward showing events on a 7-day span, so a single-day visual would basically require a completely different control, particularly if you wanted to see a grid with time of day, etc. (i.e., an "agenda" view).

Closing as "wontfix" since a daily view really should be a completely different codebase (perhaps sharing the definition of an "event," but that's about it).
